### ISSUE TITLE
Changes on No-IP renew website

### ISSUE THREAD

**Issue by lucio-modrono** [simao-silva/noip-renewer#553]
@simao-silva , thank you very much for your great work and for sharing it with the community.

The structure of the DNS names renewal website has recently changed, I've adapted the renewal script to this new structure.

I'm sending a pull request with these changes: https://github.com/simao-silva/noip-renewer/pull/552#issue-3264252639

**Comment by djraw** [comment]
Hi @lucio-modrono , thanks for the PR but unfortunately it doesn't seem to work. I commented directly on the PR.

I guess we have to wait for @simao-silva to update the script. For me it seems to be easier now. After the script didn't work I confirmed my hosts manually today. It's now just one click of 1 button on the "Zone" table to confirm multiple hosts at once.

Unfortunately I didn't think about exporting the source of the website beforehand, that could have helped to fix the script sooner.
In case someone else with unconfirmed hosts gets here reading this - please export the sites source code when the confirm button is visible.

**Comment by djraw** [comment]
> My exporting source code, you just mean using the inspect tool on the website, right? Thanks much

Yes, in most browsers it‘s even easier, for example in Firefox you can rightclick and then „View source“. Then just copy & paste the code or just save to file. That way we can see the elements that can be used by the script/webdriver.

**Comment by danutzzzzz** [comment]
Hi, what is required from me (another suffering with the problem) to a support the resolution to this problem?

#561

**Comment by Sahibishere** [comment]
> Hi, what is required from me (another suffering with the problem) to a support the resolution to this problem?
> 
> #561 

Just use a computer and inspect the page where it says to confirm the hostname by accessing links to renew hostname through email. I will try today as I brought my school computer but I am on vacation right now but I have to renew today anyways or else my hostname expires so I will also try inspecting the page if I have enough time today. 
Thanks

**Comment by Sahibishere** [comment]
> Hi [@lucio-modrono](https://github.com/lucio-modrono) , thanks for the PR but unfortunately it doesn't seem to work. I commented directly on the PR.
> 
> I guess we have to wait for [@simao-silva](https://github.com/simao-silva) to update the script. For me it seems to be easier now. After the script didn't work I confirmed my hosts manually today. It's now just one click of 1 button on the "Zone" table to confirm multiple hosts at once.
> 
> Unfortunately I didn't think about exporting the source of the website beforehand, that could have helped to fix the script sooner. In case someone else with unconfirmed hosts gets here reading this - please export the sites source code when the confirm button is visible.

Hello, I've exported the code and removed all my hostnames I will attach as pdf.

[confirm-host.pdf](https://github.com/user-attachments/files/21696368/confirm-host.pdf)

**Comment by lucio-modrono** [comment]
> > Hi [@lucio-modrono](https://github.com/lucio-modrono) , thanks for the PR but unfortunately it doesn't seem to work. I commented directly on the PR.
> > I guess we have to wait for [@simao-silva](https://github.com/simao-silva) to update the script. For me it seems to be easier now. After the script didn't work I confirmed my hosts manually today. It's now just one click of 1 button on the "Zone" table to confirm multiple hosts at once.
> > Unfortunately I didn't think about exporting the source of the website beforehand, that could have helped to fix the script sooner. In case someone else with unconfirmed hosts gets here reading this - please export the sites source code when the confirm button is visible.
> 
> Hello, I've exported the code and removed all my hostnames I will attach as pdf. Sorry about delay I was traveling.
> 
> [confirm-host.pdf](https://github.com/user-attachments/files/21696368/confirm-host.pdf)

hello @Sahibishere , thank you for sharing this info, the exported code must be for the URL used by the project (once logged): https://my.noip.com/dynamic-dns
Is It the same that you used?

I updated the code for my last PR some days ago, could you try It again and check if it works for you?

**Comment by Sahibishere** [comment]
> > > Hi [@lucio-modrono](https://github.com/lucio-modrono) , thanks for the PR but unfortunately it doesn't seem to work. I commented directly on the PR.
> > > I guess we have to wait for [@simao-silva](https://github.com/simao-silva) to update the script. For me it seems to be easier now. After the script didn't work I confirmed my hosts manually today. It's now just one click of 1 button on the "Zone" table to confirm multiple hosts at once.
> > > Unfortunately I didn't think about exporting the source of the website beforehand, that could have helped to fix the script sooner. In case someone else with unconfirmed hosts gets here reading this - please export the sites source code when the confirm button is visible.
> > 
> > Hello, I've exported the code and removed all my hostnames I will attach as pdf. Sorry about delay I was traveling.
> > 
> > [confirm-host.pdf](https://github.com/user-attachments/files/21696368/confirm-host.pdf)
> 
> hello @Sahibishere , thank you for sharing this info, the exported code must be for the URL used by the project (once logged): https://my.noip.com/dynamic-dns
> Is It the same that you used?
> 
> I updated the code for my last PR some days ago, could you try It again and check if it works for you?

Yes, that is one I used, I just dynamic DNS email I got to renew. How do I use PR? I had already renewed though but I can try again just seeing if it go throughs successfully.

**Comment by sm622** [comment]
https://my.noip.com/dynamic-dns now redirects to https://my.noip.com/dns/records

**Comment by sm622** [comment]
[noip_surce code.txt](https://github.com/user-attachments/files/21763697/noip_surce.code.txt)

attaching the source code 
https://my.noip.com/dynamic-dns     -->now redirects to ->    https://my.noip.com/dns/records

look for `                                    <div class="d-flex flex-row gap-16 align-items-center">
                                        <button hx-get="https://my.noip.com/ajax/host/89834545/touch" hx-swap="none"
                                            class="btn btn btn-success btn-thirtyfive d-flex align-items-center">
                                            Confirm
                                        </button>
                                        <button type="button" class="close"
                                            onclick="handleHostExpirationBannerClose('expiration-banner-hostname-*.yourdomain.ddns.net')"><i
                                                class="fa fa-multiply"></i></button>
                                    </div>`

**Comment by alirz1** [comment]
i updated to the latest and still getting the same error as documented in #561

**Comment by simao-silva** [comment]
@alirz1 given the output provide, looks like you are not using any of the images I shared above:

> Hi everyone, Please try running the script again using one of the images below:
> 
> * `simaofsilva/noip-renewer:pr-583-alpine`
> * `simaofsilva/noip-renewer:pr-583-debian`

Please try with one of these images.

**Comment by Kucharskov** [comment]
Im also getting an error:

```
Status: Downloaded newer image for simaofsilva/noip-renewer:pr-583-alpine
Using user agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
Opening browser
Login successful
Host confirmation phase
Host "REDACTED" needs confirmation
Host "REDACTED" confirmed
Host "REDACTED" needs confirmation
Error:  Message: Element <button class="btn btn-success btn-thirtyfive d-flex align-items-center htmx-request"> is not clickable at point (1261,329) because another element <div class="d-flex flex-row gap-16 align-items-center"> obscures it; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementclickinterceptedexception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
ElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:351:5
webdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:175:11
interaction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:134:11
clickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:327:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:210:31

Logging off```

Its important to notice that `REDACTED` value is all the same - script detects confirmation of the same domain two times.

**Comment by danutzzzzz** [comment]
> Im also getting an error:
> 
> ```
> Status: Downloaded newer image for simaofsilva/noip-renewer:pr-583-alpine
> Using user agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
> Opening browser
> Login successful
> Host confirmation phase
> Host "REDACTED" needs confirmation
> Host "REDACTED" confirmed
> Host "REDACTED" needs confirmation
> Error:  Message: Element <button class="btn btn-success btn-thirtyfive d-flex align-items-center htmx-request"> is not clickable at point (1261,329) because another element <div class="d-flex flex-row gap-16 align-items-center"> obscures it; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementclickinterceptedexception
> Stacktrace:
> RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
> WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
> ElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:351:5
> webdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:175:11
> interaction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:134:11
> clickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:327:29
> receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:210:31
> 
> Logging off
> ```
> 
> Its important to notice that `REDACTED` value is all the same - script detects confirmation of the same domain two times.
> 
> # Edit
> But when i logged into noip i saw that my hostname was confirmed!

I'm getting the same as you, it confirms ones host and then fails on the second using `simaofsilva/noip-renewer:pr-583-debian`

If i run the process 3x then all hosts get confirmed/renewed. 

```
Status: Downloaded newer image for simaofsilva/noip-renewer:pr-583-debian
Using user agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
Opening browser
Login successful
Host confirmation phase
Host "REDACTED" needs confirmation
Host "REDACTED" confirmed
Host "REDACTED" needs confirmation
Error:  Message: The element with the reference 1efbf761-b036-4381-b0c5-35bfde74112e is stale; either its node document is not the active document, or it is no longer connected to the DOM; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#staleelementreferenceexception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
StaleElementReferenceError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:725:5
getKnownElement@chrome://remote/content/marionette/json.sys.mjs:401:11
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:259:20
cloneObject@chrome://remote/content/marionette/json.sys.mjs:59:24
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:289:16
json.deserialize@chrome://remote/content/marionette/json.sys.mjs:293:10
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:73:30

Logging off
```

**Comment by simao-silva** [comment]
@ThatGuyJon, @Kucharskov, @danutzzzzz and @diepeterpan,
Please try running the script again using one of the images below:
- `simaofsilva/noip-renewer:pr-583-alpine@sha256:1853dfd95dad6b9b9f800546871ccbcd9a468f44f7ff5d14f51f4d6a72f025be`
- `simaofsilva/noip-renewer:pr-583-debian@sha256:2b59a5528613d192f490e5671770521697ec3f2153ff6de677c1966de76ef7b2 `

**Comment by redneckeyeball** [comment]
on Synology Docker image, using this command
docker run --rm --env NO_IP_USERNAME=<EMAIL> --env NO_IP_PASSWORD=<PASSWORD> --env NO_IP_TOTP_KEY=<NOIP TOTP KEY> simaofsilva/noip-renewer:pr-583-debian

This seems to work now !

Task Scheduler has completed a scheduled task.

Task: Update no-ip
Start time: Thu, 18 Sep 2025 04:45:01 +0200
Stop time: Thu, 18 Sep 2025 04:46:42 +0200
Current status: 0 (Normal)
Standard output/error:
Using user agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
Opening browser
Login successful
Host confirmation phase
No host requires confirmation
Finished
Logging off

**Comment by Kucharskov** [comment]
I got mail for confirmation today. So i tried this:
``docker run --rm --env NO_IP_USERNAME="" --env NO_IP_PASSWORD="" --env NO_IP_TOTP_KEY="" simaofsilva/noip-renewer:pr-583-alpine@sha256:1853dfd95dad6b9b9f800546871ccbcd9a468f44f7ff5d14f51f4d6a72f025be``

And thats oputput:
```
Using user agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
Opening browser
Login successful
Host confirmation phase
Host "REDACTED" needs confirmation
Host "REDACTED" confirmed
1 host confirmed
Finished
Logging off
```

And its correctly confirmed on webiste!
So I think we got it ;)

**Comment by diepeterpan** [comment]
> > i updated to the latest and still getting errors.
> > `Using user agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Safari/605.1.15" Opening browser Login successful Traceback (most recent call last): File [35m"/app/renew.py" [0m, line [35m254 [0m, in [35m<module> [0m [31mbrowser.find_element [0m [1;31m(by=By.ID, value="host-panel") [0m [31m~~~~~~~~~~~~~~~~~~~~ [0m [1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [0m File [35m"/opt/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py" [0m, line [35m926 [0m, in [35mfind_element [0m return [31mself.execute [0m [1;31m(Command.FIND_ELEMENT, {"using": by, "value": value}) [0m["value"] [31m~~~~~~~~~~~~ [0m [1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [0m File [35m"/opt/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py" [0m, line [35m458 [0m, in [35mexecute [0m [31mself.error_handler.check_response [0m [1;31m(response) [0m [31m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [0m [1;31m^^^^^^^^^^ [0m File [35m"/opt/venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py" [0m, line [35m232 [0m, in [35mcheck_response [0m raise exception_class(message, screen, stacktrace) [1;35mselenium.common.exceptions.NoSuchElementException [0m: [35mMessage: Unable to locate element: [id="host-panel"]; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception Stacktrace: RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8 WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5 NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5 dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16 [0m`
> 
> I am also getting this error and had to manually login to the site to confirm my hostnames :-(

**latest** still gives the same error, but I then tried **pr-583** and it worked and solved the problem.  Thanks.
